name: taukeet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  go_router: ^10.1.2

  adhan_dart:
    git:
      url: https://github.com/taukeet/adhan_dart.git
  location: ^5.0.3
  geocoding: ^2.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  test: ^1.24.3

flutter:
  uses-material-design: true
  fonts:
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-Regular.ttf
